name: Update Checker

env:
  REPO_URL: https://github.com/cmliu/edgetunnel
  REPO_BRANCH: main
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      run: sudo timedatectl set-timezone "$TZ"

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH edgetunnel
        cd edgetunnel
        echo "commitHash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - name: Get Cache Commit Hash
      id: cacheHash
      run: |
        cacheHash=$(curl -skL https://api.github.com/repos/hubbylei/edgetunnel/releases/latest | jq -r .body)
        echo "commitHash=${cacheHash}" >> "$GITHUB_OUTPUT"

    - name: Compare Commit Hash
      id: compare
      run: |
        cachehash="${{ steps.cacheHash.outputs.commitHash }}"
        if [ "${cachehash}" == "${{ steps.getHash.outputs.commitHash }}" ];then
          echo "build=false" >> "$GITHUB_OUTPUT"
        else
          echo "${{ steps.getHash.outputs.commitHash }}" > release.txt
          echo "tag=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
          echo "build=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Trigger build
      if: steps.compare.outputs.build == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        event-type: obfuscator

    - name: Save New Commit Hash
      if: steps.compare.outputs.build == 'true'
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.compare.outputs.tag }}
        body_path: release.txt

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
